### ISSUE TITLE
Witness Demo Instructions not working

### ISSUE THREAD

**Issue by htcarr3** [spruceid/rebase#41]
See error image attached below. Following exact instructions for Rebase demo app, wrangler expects some script file.

![image](https://user-images.githubusercontent.com/9591402/206017370-3bbddc54-d8a0-4374-9a8f-f7c1f774f826.png)

**Comment by krhoda** [comment]
Based on the information I have, I suspect that `wrangler dev` was not run in the `rebase/demo/witness` directory, or that a `wrangler.toml` was not created at that directory with the needed contents, but without more info, I can't speculate further. The [wrangler dev](https://developers.cloudflare.com/workers/wrangler/commands/#dev) documentation mentions that no arguments are needed if the `wrangler.toml` is correctly configured.

The current Rebase documentation is about to receive a major overhaul so hopefully the exact steps needed to run the demo will be clearer after the open PR (#40) merges. Because Rebase is not published to crates.io (nor is it's major dependency: [ssi](https://github.com/spruceid/ssi)), it's not the easiest library to work with currently. We should be reaching that point soon, so stay tuned for more details there! 

In the meantime, feel free to make use of our deployed witness worker at https://rebasedemo.spruceid.workers.dev you should be able to hit `/instructions`, `/statement`, and `/witness` as expected, also take a look at https://rebase.pages.dev which has a graphical front-end pointed to the worker linked above.

I'm going to close this for now, but if you still have problems after #40 closes, please feel free to re-open. Thanks for the interest!

**Comment by htcarr3** [comment]
I can confirm that I am running this from inside the witness directory, copied the example wrangler.toml file from the example (which is parsed just fine by wrangler, it throws out some warnings about unnecessary variables set), following the directions as written. It still expects some entrypoint file, which I do not see in the project. I will keep an eye on #40 merge
